# Enable GraphiQL playground
spring.graphql.graphiql.enabled=true

# Optional: customize the path (default is /graphiql)
# spring.graphql.graphiql.path=/playground

# Optional: show schema in GraphiQL
spring.graphql.schema.printer.enabled=true
# This forces Spring to log the exact moment it chooses a dialect
spring.r2dbc.url=r2dbc:mssql://graphqlomnistore:graphqlomnistore@localhost:1433/graphqlomnistore?trustServerCertificate=true
