# 1. Show the high-level Request/Response (GET/POST, URL, Headers)
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE

# 2. (Optional) Show the specific Netty headers and payload details
#logging.level.reactor.netty.http.client=DEBUG
# Try this format (replacing 'javatdslib' with whatever string your provider returns in getDriver())
spring.r2dbc.url=r2dbc:mssql://graphqlomnistore:graphqlomnistore@localhost:1433/graphqlomnistore?trustServerCertificate=true